Pausenansicht wurde angepasst
neuro-inclusive-transit/mobile-app pull request #45
Opened 2023-08-22 09:20 UTC by katrinhaa

2023-08-22 09:26 UTC, katrinhaa commented on app/views/liveView/Main.svelte
> +        <Button column={0} columnSpan={3} text="Pause beendet" icon="local_cafe" iconPosition="pre" on:tap={togglePause} />
evtl Icon zu "check" ändern? 
Button-text alternative überlegen

2023-08-22 10:25 UTC, finnge requested changes
What about changing the cup icon in the middle to something like this: https://fonts.google.com/icons?selected=Material%20Icons%3Amotion_photos_paused%3A

@Libao1 @leo-3108

2023-08-22 10:25 UTC, finnge commented on app/views/liveView/Main.svelte
> +        <Button column={0} columnSpan={3} text="Pause beendet" icon="local_cafe" iconPosition="pre" on:tap={togglePause} />
```suggestion
        <Button column={0} columnSpan={3} text="Pause beenden" icon="local_cafe" iconPosition="pre" on:tap={togglePause} />
```

2023-08-22 10:25 UTC, finnge commented on app/views/liveView/Main.svelte
> +        <Button column={0} columnSpan={3} text="Pause beendet" icon="local_cafe" iconPosition="pre" on:tap={togglePause} />
i like

2023-08-23 13:33 UTC, katrinhaa commented on app/views/liveView/Main.svelte
> +        <Button column={0} columnSpan={3} text="Pause beendet" icon="local_cafe" iconPosition="pre" on:tap={togglePause} />
ist mit dem n dann leider zu lang und der Button wird bei mir nicht mehr komplett angezeigt... 
"Pause vorbei" ginge glaub ich

2023-09-05 12:27 UTC, finnge approved these changes

2023-09-05 12:27 UTC, merged